# Generated by Django 2.2.12 on 2020-05-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200505_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=400, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Patient')),
                ('shared_with', models.ManyToManyField(to='customers.Doctor')),
            ],
        ),
    ]
