# Generated by Django 2.2.12 on 2020-05-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200505_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
