# Generated by Django 2.2.12 on 2020-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_records',
            name='shared_with',
            field=models.ManyToManyField(blank=True, to='customers.Doctor'),
        ),
    ]
