# Generated by Django 2.2.12 on 2020-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20200506_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timing',
            field=models.DateTimeField(null=True),
        ),
    ]
