# Generated by Django 2.2.12 on 2020-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_appointment_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
