# Generated by Django 2.2.12 on 2020-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20200506_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://www.pngitem.com/middle/ooRhiJ_transparent-users-icon-png-flat-user-icon-png/', max_length=400, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.CharField(blank=True, default='https://www.pngitem.com/middle/ooRhiJ_transparent-users-icon-png-flat-user-icon-png/', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://www.pngitem.com/middle/ooRhiJ_transparent-users-icon-png-flat-user-icon-png/', max_length=400, null=True, upload_to=''),
        ),
    ]
